---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
      - "policy"

    resources:
      - secrets
      - services
      - policy
      - poddisruptionbudgets
      - pods
      - pods/exec
      - pods/log
      - namespaces
      - configmaps
      - podpresets
      - podpresets/status
      - podpresets/finalizers    
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - autoscaling
      - deletecollection   
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers.autoscaling
      - horizontalpodautoscalers.extensions      
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - autoscaling
      - deletecollection   
  - apiGroups:
      - apps
      - redhatcop.redhat.io
    resources:
      - podpresets
      - podpresets/status
      - podpresets/finalizers    
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - podpresets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for dataproxy.jankul02/v1alpha1, Kind: ZookeeperSet
  ##
  - apiGroups:
      - dataproxy.jankul02
    resources:
      - zookeepersets
      - zookeepersets/status
      - zookeepersets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for dataproxy.jankul02/v1alpha1, Kind: ZkConfig
  ##
  - apiGroups:
      - dataproxy.jankul02
    resources:
      - zkconfigs
      - zkconfigs/status
      - zkconfigs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

      
  - apiGroups:
      - redhatcop.redhat.io
    resources:
      - podpresets
      - podpresets/status
      - podpresets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch


#+kubebuilder:scaffold:rules
