# permissions for end users to edit zkconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zkconfig-editor-role
rules:
- apiGroups:
  - dataproxy.jankul02
  resources:
  - zkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataproxy.jankul02
  resources:
  - zkconfigs/status
  verbs:
  - get
