# permissions for end users to view zookeepersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeperset-viewer-role
rules:
- apiGroups:
  - dataproxy.jankul02
  resources:
  - zookeepersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataproxy.jankul02
  resources:
  - zookeepersets/status
  verbs:
  - get
