apiVersion: v1
kind: Secret
metadata:
  name: zksecrets2
  namespace: default
  labels:
    app: zk
type: Opaque
data:
  username: YWRtaW4=
  password: YXFxZHFxYXFxMzQ1Mjg=
  api: aHR0cHM6Ly9hcGkuZXhhbXBsZS5jb20=